version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      MONGO_URI: mongodb://mongodb:27017/task_management
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.11-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: task_management
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
