services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGODB_URI: mongodb://localhost:27017/task_management
    networks:
      - api_server
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  api:
    container_name: api-container
    image: api:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    environment:
      NODE_ENV: development
      JWT_SECRET: secret
      JWT_EXPIRES_IN: 24h
    depends_on:
      - mongodb
    networks:
      - api_server

networks:
  api_server:
    driver: bridge
